
services:
  fastapi:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: F-API



  test:
    build: .
    container_name: F-API-TEST
    environment:
      - LOG_FILE=/log.txt
      - PYTHONPATH=/app  # Agregar la ruta del código fuente
    volumes:
      - .:/app
      - ./tests:/tests
    command: pytest tests/
    